package com.nttdata.utils.reporter;

public class HtmlTemplate {
	
	public static final String TEMPLATE = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"es\">\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Informe de Ejecuciones de Casos de Prueba</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: Arial, sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            height: 100vh;\r\n"
			+ "        }\r\n"
			+ "        header {\r\n"
			+ "            background-color: #fff;\r\n"
			+ "            padding: 10px;\r\n"
			+ "            color: #009ca6;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "        .banner {\r\n"
			+ "            background-color: #4CAF50;\r\n"
			+ "            color: white;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding: 10px;\r\n"
			+ "            margin-bottom: 10px;\r\n"
			+ "        }\r\n"
			+ "			.boton-bonito {\r\n"
			+ "      		display: inline-block;\r\n"
			+ "      		padding: 10px 20px;\r\n"
			+ "      		font-size: 16px;\r\n"
			+ "      		text-align: center;\r\n"
			+ "      		text-decoration: none;\r\n"
			+ "      		background-color: #2196f3;\r\n"
			+ "      		color: white;\r\n"
			+ "      		border-radius: 5px;\r\n"
			+ "      		border: none;\r\n"
			+ "      		transition: background-color 0.3s;\r\n"
			+ "      		cursor: pointer;\r\n"
			+ "    		}\r\n"
			+ "    		.boton-bonito:hover {\r\n"
			+ "      		background-color: #2196f3;\r\n"
			+ "    		}\r\n"
			+ "        nav {\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            width: 20%;\r\n"
			+ "            background-color: #f2f2f2;\r\n"
			+ "            padding: 10px;\r\n"
			+ "            margin-top: 10px;\r\n"
			+ "			   height: -webkit-fill-available;        }\r\n"
			+ "        nav a {\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            padding: 8px;\r\n"
			+ "            color: #333;\r\n"
			+ "            font-weight: bold;\r\n"
			+ "            border-radius: 5px;\r\n"
			+ "            margin-bottom: 5px;\r\n"
			+ "            transition: background-color 0.3s;\r\n"
			+ "        }\r\n"
			+ "        nav a:hover {\r\n"
			+ "            background-color: #ddd;\r\n"
			+ "        }\r\n"
			+ "        .content {\r\n"
			+ "            flex: 1;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-wrap: wrap;\r\n"
			+ "            padding-left: 20px;\r\n"
			+ "            overflow-y: auto;\r\n"
			+ "        }\r\n"
			+ "        .test-case {\r\n"
			+ "            border: 1px solid #ddd;\r\n"
			+ "            margin: 10px;\r\n"
			+ "            padding: 10px;\r\n"
			+ "            display: block;\r\n"
			+ "        }\r\n"
			+ "        .test-case img {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            height: auto;\r\n"
			+ "            margin-top: 10px;\r\n"
			+ "            cursor: pointer;\r\n"
			+ "        }\r\n"
			+ "        .modal {\r\n"
			+ "            display: none;\r\n"
			+ "            position: fixed;\r\n"
			+ "            top: 0;\r\n"
			+ "            left: 0;\r\n"
			+ "            width: 100%;\r\n"
			+ "            height: 100%;\r\n"
			+ "            background-color: rgba(0, 0, 0, 0.7);\r\n"
			+ "            justify-content: center;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .modal-content {\r\n"
			+ "            background-color: #fefefe;\r\n"
			+ "            padding: 20px;\r\n"
			+ "            max-width: 80%;\r\n"
			+ "            max-height: 80%;\r\n"
			+ "            overflow: auto;\r\n"
			+ "        }\r\n"
			+ "        .close {\r\n"
			+ "            color: #aaa;\r\n"
			+ "            float: right;\r\n"
			+ "            font-size: 28px;\r\n"
			+ "            font-weight: bold;\r\n"
			+ "            cursor: pointer;\r\n"
			+ "        }\r\n"
			+ "        .passed {\r\n"
			+ "            background-color: #4CAF50;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "			.passed-step {\r\n"
			+ "            color: #4CAF50;\r\n"
			+ "        }        .failed {\r\n"
			+ "            background-color: #f44336;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "        .failed-step {\r\n"
			+ "            color: #f44336;\r\n"
			+ "        }\r\n"
			+ "        .evidencia {\r\n"
			+ "            width: 20px;\r\n"
			+ "            height: 20px;\r\n"
			+ "            margin-left: 5px;\r\n"
			+ "            cursor: pointer;\r\n"
			+ "            font-size: xx-small;\r\n"
			+ "        }\r\n"
			+ "        .nav-buttons {\r\n"
			+ "            position: absolute;\r\n"
			+ "            bottom: 10px;\r\n"
			+ "            left: 50%;\r\n"
			+ "            transform: translateX(-50%);\r\n"
			+ "        }\r\n"
			+ "        .nav-buttons button {\r\n"
			+ "            background-color: #4CAF50;\r\n"
			+ "            color: white;\r\n"
			+ "            border: none;\r\n"
			+ "            border-radius: 5px;\r\n"
			+ "            padding: 8px 16px;\r\n"
			+ "            margin: 0 5px;\r\n"
			+ "            cursor: pointer;\r\n"
			+ "        }\r\n"
			+ "        .nav-buttons button:hover {\r\n"
			+ "            background-color: #45a049;\r\n"
			+ "        }\r\n"
			+ "        #evidenceCounter {\r\n"
			+ "            margin: 0 10px;\r\n"
			+ "            font-size: 20px;\r\n"
			+ "            color: white;\r\n"
			+ "        }\r\n"
			+ "		   #idTituloEvidencia {\r\n"
			+ "            margin: 0 10px;\r\n"
			+ "            font-size: 30px;\r\n"
			+ "            color: black;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "<body>\r\n"
			+ "\r\n"
			+ "    <header>\r\n"
			+ "			<img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRACAiDIPFuHlHMUSlkxM9kIfGRzQsyJ6fS5pymj6PuXn6Unaq7-XFtWbb3Bab4XHuUUA&usqp=CAU\"/>"
			+ "\r\n"
			+ "        	<h1>Informe de Ejecuciones de Casos de Prueba</h1>\r\n"
			+ "    </header>\r\n"
			+ "\r\n"
			+ "    <div class=\"banner\" id=\"globalResult\">\r\n"
			+ "        @VARIABLE_RESULTADO\r\n"
			+ "    </div>\r\n"
			+ "\r\n"
			+ "    <div class=\"content\" id=\"content\">\r\n"
			+ "        <nav id=\"testCasesNav\">\r\n"
			+ "            <!-- Enlaces se cargarán dinámicamente aquí -->\r\n"
			+ "        </nav>\r\n"
			+ "\r\n"
			+ "        <div id=\"testCasesContent\" style=\"flex: inherit;\">\r\n"
			+ "            <!-- Contenido de los casos de prueba se cargarán dinámicamente aquí -->\r\n"
			+ "        </div>\r\n"
			+ "    </div>\r\n"
			+ "\r\n"
			+ "    <!-- Modal para mostrar la imagen en grande -->\r\n"
			+ "    <div id=\"myModal\" class=\"modal\">\r\n"
			+ "        <div class=\"modal-content\">\r\n"
			+ "			   <label id=\"idTituloEvidencia\"></label>"	
			+ "            <span class=\"close\" onclick=\"hideModal()\">&times;</span>\r\n"
			+ "            <img id=\"modalImage\" style=\"max-width: 100%; max-height: 100%;\" alt=\"Evidencia Ampliada\">\r\n"
			+ "            <div class=\"nav-buttons\">\r\n"
			+ "                <button id=\"prevButton\" onclick=\"showPrevImage()\">Anterior</button>\r\n"
			+ "                <span id=\"evidenceCounter\"></span>\r\n"
			+ "                <button id=\"nextButton\" onclick=\"showNextImage()\">Siguiente</button>\r\n"
			+ "            </div>\r\n"
			+ "        </div>\r\n"
			+ "    </div>\r\n"
			+ "\r\n"
			+ "    <script>\r\n"
			+ "        function toggleTestCase(testCaseId) {\r\n"
			+ "            ocultarDivs();\r\n"
			+ "            var testCase = document.getElementById(testCaseId);\r\n"
			+ "            testCase.style.display = testCase.style.display === 'none' || testCase.style.display === '' ? 'block' : 'none';\r\n"
			+ "\r\n"
			+ "            var indicator = document.querySelector(`#${testCaseId} .indicator`);\r\n"
			+ "            currentTest = getTestCaseById(testCaseId);\r\n"
			+ "\r\n"
			+ "			   var div = document.getElementById('content');\r\n"
			+ "            div.scrollTop = 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        function ocultarDivs() {\r\n"
			+ "            // Obtén todos los elementos con la clase \"test-case\"\r\n"
			+ "            var elementos = document.querySelectorAll('.test-case');\r\n"
			+ "\r\n"
			+ "            // Itera sobre los elementos y ocúltalos\r\n"
			+ "            elementos.forEach(function(elemento) {\r\n"
			+ "              elemento.style.display = 'none';\r\n"
			+ "            });\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        function getTestCaseById(testCaseId) {\r\n"
			+ "            return casosDePrueba.find(caso => caso.id === testCaseId);\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "        let currentImageIndex = 0;\r\n"
			+ "        let currentImages = [];\r\n"
			+ "        let currentTest;\r\n"
			+ "        let currentStep;\r\n"
			+ "\r\n"
			+ "        function showModal(step) {\r\n"
			+ "            currentImageIndex = 0;\r\n"
			+ "            currentStep = currentTest.pasos[step];\r\n"
			+ "            currentImages = currentStep.evidencias;\r\n"
			+ "            updateModalContent();\r\n"
			+ "            document.getElementById(\"myModal\").style.display = \"flex\";\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        function hideModal() {\r\n"
			+ "            document.getElementById(\"myModal\").style.display = \"none\";\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        function showPrevImage() {\r\n"
			+ "            if (currentImageIndex > 0) {\r\n"
			+ "                currentImageIndex--;\r\n"
			+ "                updateModalContent();\r\n"
			+ "            }\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        function showNextImage() {\r\n"
			+ "            if (currentImageIndex < currentImages.length - 1) {\r\n"
			+ "                currentImageIndex++;\r\n"
			+ "                updateModalContent();\r\n"
			+ "            }\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        function updateModalContent() {\r\n"
			+ "            document.getElementById(\"modalImage\").src = currentImages[currentImageIndex].data;\r\n"
			+ "            document.getElementById(\"prevButton\").disabled = currentImageIndex === 0;\r\n"
			+ "            document.getElementById(\"nextButton\").disabled = currentImageIndex === currentImages.length - 1;\r\n"
			+ "\r\n"
			+ "            const evidenceCounter = document.getElementById(\"evidenceCounter\");\r\n"
			+ "            evidenceCounter.textContent = `${currentImageIndex + 1}/${currentImages.length}`;\r\n"
			+ "\r\n"
			+ "            const tituloEvidencia = document.getElementById(\"idTituloEvidencia\");\r\n"
			+ "            tituloEvidencia.textContent = `${currentStep.descripcion} : ${currentStep.evidencias[currentImageIndex].text}`;\r\n"
			+ "        }"
			+ "\r\n"
			+ "        // Cargar datos desde un archivo JSON (simulado aquí)\r\n"
			+ "        const casosPassed = @VARIABLE_CASOS_DE_PASSED;\r\n"
			+ "        const casosFailed = @VARIABLE_CASOS_DE_FAILED;\r\n"
			+ "        const casosTotal = @VARIABLE_CASOS_DE_TOTAL;\r\n"
			+ "\r\n"
			+ "        var coloredDiv = document.getElementById('globalResult');\r\n"
			+ "        var porcentajeVerde = (casosPassed / casosTotal) * 100;\r\n"
			+ "        var porcentajeRojo = 100 - porcentajeVerde;\r\n"
			+ "        coloredDiv.style.background = 'linear-gradient(to right, #4CAF50 ' + porcentajeVerde + '%, #f44336 ' + porcentajeRojo + '%)';"
			+ "\r\n"
			+ "        const casosDePrueba = @VARIABLE_CASOS_DE_PRUEBA;\r\n"
			+ "\r\n"
			+ "        // Cargar casos de prueba en el panel de navegación y contenido\r\n"
			+ "        const testCasesNav = document.getElementById('testCasesNav');\r\n"
			+ "        const testCasesContent = document.getElementById('testCasesContent');\r\n"
			+ "\r\n"
			+ "        casosDePrueba.forEach(caso => {\r\n"
			+ "            // Enlaces en el panel de navegación\r\n"
			+ "            const navLink = document.createElement('a');\r\n"
			+ "            navLink.href = '#';\r\n"
			+ "			   navLink.className = caso.resultadoColor;\r\n"
			+ "            navLink.onclick = () => toggleTestCase(caso.id);\r\n"
			+ "            navLink.innerHTML = `<span class=\"case-name\">[${caso.id}]${caso.nombre}</span>`;\r\n"
			+ "            testCasesNav.appendChild(navLink);\r\n"
			+ "\r\n"
			+ "            // Contenido de los casos de prueba\r\n"
			+ "            const testCaseDiv = document.createElement('div');\r\n"
			+ "            testCaseDiv.id = caso.id;\r\n"
			+ "            testCaseDiv.className = 'test-case';\r\n"
			+ "            testCaseDiv.style.display = 'none'; // Mostrar todos inicialmente\r\n"
			+ "            testCaseDiv.innerHTML = `\r\n"
			+ "                <h2>[${caso.id}]${caso.nombre}</h2>\r\n"
			+ "                <p> <b>Resultado: <label class=\"${caso.resultadoColor}\" style=\"font-size: x-large;\">${caso.resultado}</label></b></p>\r\n"
			+ "                <p><b>Fecha de Inicio:</b> ${caso.start}<br>\r\n"
			+ "                <b>Fecha de Termino:</b> ${caso.finish}<br>\r\n"
			+ "                <b>Duracion:</b> ${caso.duracion}</p>\r\n"
			+ "					${caso.error}"
			+ "\r\n"
			+ "				   <ul>${caso.testAttachs.map(attach => `<code style=\"word-break: break-word;\">${attach.name}: ${attach.text}</code></br>`).join('')}</ul>"
			+ "                <h3>Pasos:</h3>\r\n"			
			+ "                <ol>${caso.pasos.map((paso, index) => `\r\n"
			+ "                    <li>\r\n"
			+ "                        <label class=\"${paso.resultado}-step\">${paso.descripcion}</label>\r\n"
			+ "                            <a href=\"#\" class=\"evidencia\" onclick=\"showModal(${index})\">[Ver Evidencia]</a>\r\n"
			+ "                    </li>\r\n"
			+ "                `).join('')}</ol>\r\n"
			+ "            `;\r\n"
			+ "            testCasesContent.appendChild(testCaseDiv);\r\n"
			+ "         });\r\n"
			+ "			function toggleSpan(testCaseId) {\r\n"
			+ "            	var span = document.getElementById('error-' + testCaseId);\r\n"
			+ "            	span.style.display = (span.style.display === 'none' || span.style.display === '') ? 'inline' : 'none';\r\n"
			+ "        	}"
			+ "\r\n"
			+ "    </script>\r\n"
			+ "\r\n"
			+ "</body>\r\n"
			+ "</html>\r\n"
			+ "";

}
